# Used by quay.io to trigger developer builds
FROM quay.io/redhat-cne/openshift-origin-release:golang-1.17 AS go-builder
WORKDIR /go/src/github.com/redhat-cne/hw-event-proxy-operator
COPY . .
ENV GO111MODULE=off
RUN make
# Build

FROM quay.io/redhat-cne/openshift-origin-release:base-4.10
WORKDIR /
COPY --from=builder /go/src/github.com/redhat-cne/hw-event-proxy-operator/build/_output/bin/hw-event-proxy-operator /
COPY --from=builder /go/src/github.com/redhat-cne/hw-event-proxy-operator/bindata /bindata
USER 65532:65532

ENTRYPOINT ["/hw-event-proxy-operator"]
