apiVersion: kuttl.dev/v1beta1
kind: TestSuite

testDirs:
- tests/e2e/tests/
crdDir: config/crd/bases/

# The operator has a reconcile loop of 5 minutes, so we need to wait at least that amount of time
# before deciding to error.
timeout: 350
parallel: 1
namespace: hw-event-proxy-operator-system
