apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    service.beta.openshift.io/serving-cert-secret-name: hw-event-proxy-secret
  name: hw-event-proxy-service
  namespace: {{ .Namespace }}
  labels:
    app: hw-event-proxy
spec:
  ports:
    - name: hw-event
      port: 9087
      targetPort: 9087
    - name: https
      port: 8443
      targetPort: https
  selector:
    app: hw-event-proxy
  type: ClusterIP